export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const SET_ALL_EVENTS = 'SET_ALL_EVENTS';
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT';
export const SET_CURRENT_STATES = 'SET_CURRENT_STATES';
export const SET_CURRENT_MARKETS = 'SET_CURRENT_MARKETS';
export const SET_CURRENT_CONTRACTS = 'SET_CURRENT_CONTRACTS';
export const SET_LOADING = 'SET_LOADING';
